### ISSUE TITLE
Error: "no file reader for yml available"

### ISSUE THREAD

**Issue by emresaracoglu** [thewunder/conphigure#1]
Hi,

I still get this error even though I created the YML File. What could be the reason for this?

Thank you.

<hr>

_PHP:_

```
$yamlFileApp = Conphigure::create();
$yamlFileApp->read('app/app.yml');
```

_YML:_

```
# YML Test file
app:
  updatechannel: example.com
  updatepackage: development
```

_Error:_

> Fatal error: Uncaught Conphigure\Exception\ConfigurationFileException: Error reading configuration file app/app.yml no file reader for yml available in /home/example/public_html/vendor/thewunder/conphigure/src/Conphigure.php:257 Stack trace: #0 /home/example/public_html/vendor/thewunder/conphigure/src/Conphigure.php(212): Conphigure\Conphigure->getFileReader('app/app.yml') #1 /home/example/public_html/app/core/appConfig.php(28): Conphigure\Conphigure->read('app/app.yml') #2 /home/example/public_html/index.php(3): include('/home/example/...') #3 {main} thrown in /home/example/public_html/vendor/thewunder/conphigure/src/Conphigure.php on line 257

**Comment by thewunder** [comment]
You need to install symfony/yaml

```
composer require symfony/yaml

**Comment by emresaracoglu** [comment]
Thank you @thewunder
